Hotfix/making blog site specific to ciaranmckenna
ciaranmckenna/ciaranmckenna.com pull request #2
Opened 2019-01-29 22:11 UTC by ciaranmckenna

2019-01-30 08:33 UTC, barrymcgee requested changes
Just found one small typo 👍🏻

2019-01-30 08:33 UTC, barrymcgee commented on src/components/header.js
> +          Here I occasionly discuss technology, politics &amp; healthy living.
```suggestion
          Here I occasionally discuss technology, politics &amp; healthy living.
```

2019-01-30 08:46 UTC, barrymcgee commented
@ciaranmckenna Also note, conventation dictates;

- Branch names should be short and lowercase
- You have this branch in a 'hotfix' folder. a 'hotfix' is the term used for small unavoidable changes to fix a production bug outside of your regular development cycle.

2019-01-30 21:22 UTC, ciaranmckenna commented on src/components/header.js
> +          Here I occasionly discuss technology, politics &amp; healthy living.
Cool, thanks.

2019-02-01 10:58 UTC, barrymcgee approved these changes

2019-02-01 10:58 UTC, barrymcgee commented
@ciaranmckenna This is now good to merge.

2019-02-03 21:10 UTC, ciaranmckenna commented on src/pages/about.js
> +      a teacher and head of department before joinging the world of software development.
```suggestion
      a teacher and head of department before joining the world of software development.
```

2019-02-03 21:13 UTC, ciaranmckenna commented
Reviewed in person with @barrymcgee

2019-02-03 21:14 UTC, merged