Changing colour of the headings
ciaranmckenna/ciaranmckenna.com pull request #7
Opened 2019-02-10 17:46 UTC by ciaranmckenna

On review what I think has happened here is that the global command line theme has change, not the actual change to the font on the page. Also, this change broke the link to localhost.

2019-02-11 09:24 UTC, barrymcgee requested changes

2019-02-11 09:24 UTC, barrymcgee commented on src/components/postLayout.js
> +    color: #6680244;
A hex code is so called because it should have six characters - these have seven values and are invalid.

2019-02-11 09:24 UTC, barrymcgee commented on src/components/postLayout.js
> +  color: #6680244;
Invalid hex code.

2019-02-11 09:24 UTC, barrymcgee commented on src/styles/theme.scss
> +$color-highlight: #4394ca;
This new blue colours works and looks good.

2019-02-18 21:31 UTC, barrymcgee approved these changes

2019-02-18 21:32 UTC, ciaranmckenna commented
Thanks for the approval.

2019-02-18 21:33 UTC, merged